var annotated_dup =
[
    [ "Mirai", "namespaceMirai.html", [
      [ "AppMessage", "classMirai_1_1AppMessage.html", "classMirai_1_1AppMessage" ],
      [ "AtAllMessage", "classMirai_1_1AtAllMessage.html", "classMirai_1_1AtAllMessage" ],
      [ "AtMessage", "classMirai_1_1AtMessage.html", "classMirai_1_1AtMessage" ],
      [ "AudioMessage", "classMirai_1_1AudioMessage.html", "classMirai_1_1AudioMessage" ],
      [ "AuthKeyFail", "classMirai_1_1AuthKeyFail.html", "classMirai_1_1AuthKeyFail" ],
      [ "BotAccountEvent", "classMirai_1_1BotAccountEvent.html", "classMirai_1_1BotAccountEvent" ],
      [ "BotGroupPermissionChangeEvent", "classMirai_1_1BotGroupPermissionChangeEvent.html", "classMirai_1_1BotGroupPermissionChangeEvent" ],
      [ "BotInvitedJoinGroupRequestEvent", "classMirai_1_1BotInvitedJoinGroupRequestEvent.html", "classMirai_1_1BotInvitedJoinGroupRequestEvent" ],
      [ "BotJoinGroupEvent", "classMirai_1_1BotJoinGroupEvent.html", "classMirai_1_1BotJoinGroupEvent" ],
      [ "BotLeaveEvent", "classMirai_1_1BotLeaveEvent.html", "classMirai_1_1BotLeaveEvent" ],
      [ "BotLeaveEventActive", "classMirai_1_1BotLeaveEventActive.html", null ],
      [ "BotLeaveEventDisband", "classMirai_1_1BotLeaveEventDisband.html", "classMirai_1_1BotLeaveEventDisband" ],
      [ "BotLeaveEventKick", "classMirai_1_1BotLeaveEventKick.html", "classMirai_1_1BotLeaveEventKick" ],
      [ "BotMuted", "classMirai_1_1BotMuted.html", "classMirai_1_1BotMuted" ],
      [ "BotMuteEvent", "classMirai_1_1BotMuteEvent.html", "classMirai_1_1BotMuteEvent" ],
      [ "BotOfflineEventActive", "classMirai_1_1BotOfflineEventActive.html", null ],
      [ "BotOfflineEventDropped", "classMirai_1_1BotOfflineEventDropped.html", null ],
      [ "BotOfflineEventForce", "classMirai_1_1BotOfflineEventForce.html", null ],
      [ "BotOnlineEvent", "classMirai_1_1BotOnlineEvent.html", null ],
      [ "BotReloginEvent", "classMirai_1_1BotReloginEvent.html", null ],
      [ "BotUnmuteEvent", "classMirai_1_1BotUnmuteEvent.html", "classMirai_1_1BotUnmuteEvent" ],
      [ "ClientConnectionClosedEvent", "structMirai_1_1ClientConnectionClosedEvent.html", "structMirai_1_1ClientConnectionClosedEvent" ],
      [ "ClientConnectionErrorEvent", "structMirai_1_1ClientConnectionErrorEvent.html", "structMirai_1_1ClientConnectionErrorEvent" ],
      [ "ClientConnectionEstablishedEvent", "structMirai_1_1ClientConnectionEstablishedEvent.html", "structMirai_1_1ClientConnectionEstablishedEvent" ],
      [ "ClientDevice", "structMirai_1_1ClientDevice.html", "structMirai_1_1ClientDevice" ],
      [ "ClientParseErrorEvent", "structMirai_1_1ClientParseErrorEvent.html", "structMirai_1_1ClientParseErrorEvent" ],
      [ "CommandExecutedEvent", "classMirai_1_1CommandExecutedEvent.html", "classMirai_1_1CommandExecutedEvent" ],
      [ "DiceMessage", "classMirai_1_1DiceMessage.html", "classMirai_1_1DiceMessage" ],
      [ "FaceMessage", "classMirai_1_1FaceMessage.html", null ],
      [ "FaceMessageImpl", "classMirai_1_1FaceMessageImpl.html", "classMirai_1_1FaceMessageImpl" ],
      [ "FileInfo", "structMirai_1_1FileInfo.html", "structMirai_1_1FileInfo" ],
      [ "FileMessage", "classMirai_1_1FileMessage.html", "classMirai_1_1FileMessage" ],
      [ "FilePath", "classMirai_1_1FilePath.html", "classMirai_1_1FilePath" ],
      [ "FlashImageMessage", "classMirai_1_1FlashImageMessage.html", null ],
      [ "ForwardMessage", "classMirai_1_1ForwardMessage.html", "classMirai_1_1ForwardMessage" ],
      [ "FriendInputStatusChangedEvent", "classMirai_1_1FriendInputStatusChangedEvent.html", "classMirai_1_1FriendInputStatusChangedEvent" ],
      [ "FriendMessageEvent", "classMirai_1_1FriendMessageEvent.html", "classMirai_1_1FriendMessageEvent" ],
      [ "FriendNickChangedEvent", "classMirai_1_1FriendNickChangedEvent.html", "classMirai_1_1FriendNickChangedEvent" ],
      [ "FriendRecallEvent", "classMirai_1_1FriendRecallEvent.html", "classMirai_1_1FriendRecallEvent" ],
      [ "FriendSyncMessageEvent", "classMirai_1_1FriendSyncMessageEvent.html", "classMirai_1_1FriendSyncMessageEvent" ],
      [ "GetEventType", "structMirai_1_1GetEventType.html", null ],
      [ "GetEventType< CommandExecutedEvent::GetType()>", "structMirai_1_1GetEventType_3_01CommandExecutedEvent_1_1GetType_07_08_4.html", "structMirai_1_1GetEventType_3_01CommandExecutedEvent_1_1GetType_07_08_4" ],
      [ "GetEventType< NewFriendRequestEvent::GetType()>", "structMirai_1_1GetEventType_3_01NewFriendRequestEvent_1_1GetType_07_08_4.html", "structMirai_1_1GetEventType_3_01NewFriendRequestEvent_1_1GetType_07_08_4" ],
      [ "GetEventType< NudgeEvent::GetType()>", "structMirai_1_1GetEventType_3_01NudgeEvent_1_1GetType_07_08_4.html", "structMirai_1_1GetEventType_3_01NudgeEvent_1_1GetType_07_08_4" ],
      [ "GetEventType< StrangerMessageEvent::GetType()>", "structMirai_1_1GetEventType_3_01StrangerMessageEvent_1_1GetType_07_08_4.html", "structMirai_1_1GetEventType_3_01StrangerMessageEvent_1_1GetType_07_08_4" ],
      [ "GetEventType< StrangerSyncMessageEvent::GetType()>", "structMirai_1_1GetEventType_3_01StrangerSyncMessageEvent_1_1GetType_07_08_4.html", "structMirai_1_1GetEventType_3_01StrangerSyncMessageEvent_1_1GetType_07_08_4" ],
      [ "GetEventType< TempMessageEvent::GetType()>", "structMirai_1_1GetEventType_3_01TempMessageEvent_1_1GetType_07_08_4.html", "structMirai_1_1GetEventType_3_01TempMessageEvent_1_1GetType_07_08_4" ],
      [ "GetEventType< TempSyncMessageEvent::GetType()>", "structMirai_1_1GetEventType_3_01TempSyncMessageEvent_1_1GetType_07_08_4.html", "structMirai_1_1GetEventType_3_01TempSyncMessageEvent_1_1GetType_07_08_4" ],
      [ "GetType", "structMirai_1_1GetType.html", null ],
      [ "GetType< AppMessage::GetType()>", "structMirai_1_1GetType_3_01AppMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01AppMessage_1_1GetType_07_08_4" ],
      [ "GetType< AtAllMessage::GetType()>", "structMirai_1_1GetType_3_01AtAllMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01AtAllMessage_1_1GetType_07_08_4" ],
      [ "GetType< AtMessage::GetType()>", "structMirai_1_1GetType_3_01AtMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01AtMessage_1_1GetType_07_08_4" ],
      [ "GetType< AudioMessage::GetType()>", "structMirai_1_1GetType_3_01AudioMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01AudioMessage_1_1GetType_07_08_4" ],
      [ "GetType< DiceMessage::GetType()>", "structMirai_1_1GetType_3_01DiceMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01DiceMessage_1_1GetType_07_08_4" ],
      [ "GetType< FaceMessage::GetType()>", "structMirai_1_1GetType_3_01FaceMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01FaceMessage_1_1GetType_07_08_4" ],
      [ "GetType< FileMessage::GetType()>", "structMirai_1_1GetType_3_01FileMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01FileMessage_1_1GetType_07_08_4" ],
      [ "GetType< FlashImageMessage::GetType()>", "structMirai_1_1GetType_3_01FlashImageMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01FlashImageMessage_1_1GetType_07_08_4" ],
      [ "GetType< ForwardMessage::GetType()>", "structMirai_1_1GetType_3_01ForwardMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01ForwardMessage_1_1GetType_07_08_4" ],
      [ "GetType< ImageMessage::GetType()>", "structMirai_1_1GetType_3_01ImageMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01ImageMessage_1_1GetType_07_08_4" ],
      [ "GetType< JsonMessage::GetType()>", "structMirai_1_1GetType_3_01JsonMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01JsonMessage_1_1GetType_07_08_4" ],
      [ "GetType< MarketFaceMessage::GetType()>", "structMirai_1_1GetType_3_01MarketFaceMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01MarketFaceMessage_1_1GetType_07_08_4" ],
      [ "GetType< MiraiCodeMessage::GetType()>", "structMirai_1_1GetType_3_01MiraiCodeMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01MiraiCodeMessage_1_1GetType_07_08_4" ],
      [ "GetType< MusicShareMessage::GetType()>", "structMirai_1_1GetType_3_01MusicShareMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01MusicShareMessage_1_1GetType_07_08_4" ],
      [ "GetType< PlainMessage::GetType()>", "structMirai_1_1GetType_3_01PlainMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01PlainMessage_1_1GetType_07_08_4" ],
      [ "GetType< PokeMessage::GetType()>", "structMirai_1_1GetType_3_01PokeMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01PokeMessage_1_1GetType_07_08_4" ],
      [ "GetType< QuoteMessage::GetType()>", "structMirai_1_1GetType_3_01QuoteMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01QuoteMessage_1_1GetType_07_08_4" ],
      [ "GetType< SourceMessage::GetType()>", "structMirai_1_1GetType_3_01SourceMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01SourceMessage_1_1GetType_07_08_4" ],
      [ "GetType< XmlMessage::GetType()>", "structMirai_1_1GetType_3_01XmlMessage_1_1GetType_07_08_4.html", "structMirai_1_1GetType_3_01XmlMessage_1_1GetType_07_08_4" ],
      [ "GID_t", "classMirai_1_1GID__t.html", "classMirai_1_1GID__t" ],
      [ "Group", "structMirai_1_1Group.html", "structMirai_1_1Group" ],
      [ "GroupAllowAnonymousChatEvent", "classMirai_1_1GroupAllowAnonymousChatEvent.html", "classMirai_1_1GroupAllowAnonymousChatEvent" ],
      [ "GroupAllowConfessTalkEvent", "classMirai_1_1GroupAllowConfessTalkEvent.html", "classMirai_1_1GroupAllowConfessTalkEvent" ],
      [ "GroupAllowMemberInviteEvent", "classMirai_1_1GroupAllowMemberInviteEvent.html", "classMirai_1_1GroupAllowMemberInviteEvent" ],
      [ "GroupAnnouncement", "structMirai_1_1GroupAnnouncement.html", "structMirai_1_1GroupAnnouncement" ],
      [ "GroupConfig", "structMirai_1_1GroupConfig.html", "structMirai_1_1GroupConfig" ],
      [ "GroupEntranceAnnouncementChangeEvent", "classMirai_1_1GroupEntranceAnnouncementChangeEvent.html", "classMirai_1_1GroupEntranceAnnouncementChangeEvent" ],
      [ "GroupFileInfo", "structMirai_1_1GroupFileInfo.html", "structMirai_1_1GroupFileInfo" ],
      [ "GroupMember", "structMirai_1_1GroupMember.html", "structMirai_1_1GroupMember" ],
      [ "GroupMessageEvent", "classMirai_1_1GroupMessageEvent.html", "classMirai_1_1GroupMessageEvent" ],
      [ "GroupMuteAllEvent", "classMirai_1_1GroupMuteAllEvent.html", "classMirai_1_1GroupMuteAllEvent" ],
      [ "GroupNameChangeEvent", "classMirai_1_1GroupNameChangeEvent.html", "classMirai_1_1GroupNameChangeEvent" ],
      [ "GroupRecallEvent", "classMirai_1_1GroupRecallEvent.html", "classMirai_1_1GroupRecallEvent" ],
      [ "GroupSyncMessageEvent", "classMirai_1_1GroupSyncMessageEvent.html", "classMirai_1_1GroupSyncMessageEvent" ],
      [ "HttpWsAdaptorConfig", "structMirai_1_1HttpWsAdaptorConfig.html", "structMirai_1_1HttpWsAdaptorConfig" ],
      [ "IAdaptor", "classMirai_1_1IAdaptor.html", "classMirai_1_1IAdaptor" ],
      [ "IEvent", "classMirai_1_1IEvent.html", "classMirai_1_1IEvent" ],
      [ "IllegalSession", "classMirai_1_1IllegalSession.html", "classMirai_1_1IllegalSession" ],
      [ "ILogger", "classMirai_1_1ILogger.html", "classMirai_1_1ILogger" ],
      [ "ImageMessage", "classMirai_1_1ImageMessage.html", null ],
      [ "ImageMessageImpl", "classMirai_1_1ImageMessageImpl.html", "classMirai_1_1ImageMessageImpl" ],
      [ "IMessage", "classMirai_1_1IMessage.html", "classMirai_1_1IMessage" ],
      [ "IMessageImpl", "classMirai_1_1IMessageImpl.html", "classMirai_1_1IMessageImpl" ],
      [ "JsonMessage", "classMirai_1_1JsonMessage.html", "classMirai_1_1JsonMessage" ],
      [ "MarketFaceMessage", "classMirai_1_1MarketFaceMessage.html", "classMirai_1_1MarketFaceMessage" ],
      [ "MemberCardChangeEvent", "classMirai_1_1MemberCardChangeEvent.html", "classMirai_1_1MemberCardChangeEvent" ],
      [ "MemberHonorChangeEvent", "classMirai_1_1MemberHonorChangeEvent.html", "classMirai_1_1MemberHonorChangeEvent" ],
      [ "MemberJoinEvent", "classMirai_1_1MemberJoinEvent.html", "classMirai_1_1MemberJoinEvent" ],
      [ "MemberJoinRequestEvent", "classMirai_1_1MemberJoinRequestEvent.html", "classMirai_1_1MemberJoinRequestEvent" ],
      [ "MemberLeaveEvent", "classMirai_1_1MemberLeaveEvent.html", "classMirai_1_1MemberLeaveEvent" ],
      [ "MemberLeaveEventKick", "classMirai_1_1MemberLeaveEventKick.html", "classMirai_1_1MemberLeaveEventKick" ],
      [ "MemberLeaveEventQuit", "classMirai_1_1MemberLeaveEventQuit.html", null ],
      [ "MemberMuteEvent", "classMirai_1_1MemberMuteEvent.html", "classMirai_1_1MemberMuteEvent" ],
      [ "MemberPermissionChangeEvent", "classMirai_1_1MemberPermissionChangeEvent.html", "classMirai_1_1MemberPermissionChangeEvent" ],
      [ "MemberSpecialTitleChangeEvent", "classMirai_1_1MemberSpecialTitleChangeEvent.html", "classMirai_1_1MemberSpecialTitleChangeEvent" ],
      [ "MemberUnmuteEvent", "classMirai_1_1MemberUnmuteEvent.html", "classMirai_1_1MemberUnmuteEvent" ],
      [ "MessageChain", "classMirai_1_1MessageChain.html", "classMirai_1_1MessageChain" ],
      [ "MessageTooLarge", "classMirai_1_1MessageTooLarge.html", "classMirai_1_1MessageTooLarge" ],
      [ "MiraiApiHttpException", "classMirai_1_1MiraiApiHttpException.html", "classMirai_1_1MiraiApiHttpException" ],
      [ "MiraiAudio", "structMirai_1_1MiraiAudio.html", "structMirai_1_1MiraiAudio" ],
      [ "MiraiClient", "classMirai_1_1MiraiClient.html", "classMirai_1_1MiraiClient" ],
      [ "MiraiCodeMessage", "classMirai_1_1MiraiCodeMessage.html", "classMirai_1_1MiraiCodeMessage" ],
      [ "MiraiImage", "structMirai_1_1MiraiImage.html", "structMirai_1_1MiraiImage" ],
      [ "MusicShareMessage", "classMirai_1_1MusicShareMessage.html", "classMirai_1_1MusicShareMessage" ],
      [ "NetworkException", "classMirai_1_1NetworkException.html", "classMirai_1_1NetworkException" ],
      [ "NewFriendRequestEvent", "classMirai_1_1NewFriendRequestEvent.html", "classMirai_1_1NewFriendRequestEvent" ],
      [ "NoBot", "classMirai_1_1NoBot.html", "classMirai_1_1NoBot" ],
      [ "NoElement", "classMirai_1_1NoElement.html", "classMirai_1_1NoElement" ],
      [ "NoOperateSupport", "classMirai_1_1NoOperateSupport.html", "classMirai_1_1NoOperateSupport" ],
      [ "NoSuchFile", "classMirai_1_1NoSuchFile.html", "classMirai_1_1NoSuchFile" ],
      [ "NotImplementedError", "classMirai_1_1NotImplementedError.html", null ],
      [ "NotVerifySession", "classMirai_1_1NotVerifySession.html", "classMirai_1_1NotVerifySession" ],
      [ "NudgeEvent", "classMirai_1_1NudgeEvent.html", "classMirai_1_1NudgeEvent" ],
      [ "NudgeTarget", "classMirai_1_1NudgeTarget.html", "classMirai_1_1NudgeTarget" ],
      [ "NullLogger", "classMirai_1_1NullLogger.html", "classMirai_1_1NullLogger" ],
      [ "OtherClientMessageEvent", "classMirai_1_1OtherClientMessageEvent.html", "classMirai_1_1OtherClientMessageEvent" ],
      [ "OtherClientOfflineEvent", "classMirai_1_1OtherClientOfflineEvent.html", "classMirai_1_1OtherClientOfflineEvent" ],
      [ "OtherClientOnlineEvent", "classMirai_1_1OtherClientOnlineEvent.html", "classMirai_1_1OtherClientOnlineEvent" ],
      [ "ParseError", "classMirai_1_1ParseError.html", "classMirai_1_1ParseError" ],
      [ "PermissionDenied", "classMirai_1_1PermissionDenied.html", "classMirai_1_1PermissionDenied" ],
      [ "PlainMessage", "classMirai_1_1PlainMessage.html", "classMirai_1_1PlainMessage" ],
      [ "PokeMessage", "classMirai_1_1PokeMessage.html", "classMirai_1_1PokeMessage" ],
      [ "QQ_t", "classMirai_1_1QQ__t.html", "classMirai_1_1QQ__t" ],
      [ "QuoteMessage", "classMirai_1_1QuoteMessage.html", "classMirai_1_1QuoteMessage" ],
      [ "SourceMessage", "classMirai_1_1SourceMessage.html", "classMirai_1_1SourceMessage" ],
      [ "StrangerMessageEvent", "classMirai_1_1StrangerMessageEvent.html", "classMirai_1_1StrangerMessageEvent" ],
      [ "StrangerSyncMessageEvent", "classMirai_1_1StrangerSyncMessageEvent.html", "classMirai_1_1StrangerSyncMessageEvent" ],
      [ "TempMessageEvent", "classMirai_1_1TempMessageEvent.html", "classMirai_1_1TempMessageEvent" ],
      [ "TempSyncMessageEvent", "classMirai_1_1TempSyncMessageEvent.html", "classMirai_1_1TempSyncMessageEvent" ],
      [ "TypeDismatchError", "classMirai_1_1TypeDismatchError.html", "classMirai_1_1TypeDismatchError" ],
      [ "UID_t", "classMirai_1_1UID__t.html", "classMirai_1_1UID__t" ],
      [ "User", "structMirai_1_1User.html", "structMirai_1_1User" ],
      [ "UserProfile", "structMirai_1_1UserProfile.html", "structMirai_1_1UserProfile" ],
      [ "XmlMessage", "classMirai_1_1XmlMessage.html", "classMirai_1_1XmlMessage" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< Mirai::GID_t >", "structstd_1_1hash_3_01Mirai_1_1GID__t_01_4.html", "structstd_1_1hash_3_01Mirai_1_1GID__t_01_4" ],
      [ "hash< Mirai::QQ_t >", "structstd_1_1hash_3_01Mirai_1_1QQ__t_01_4.html", "structstd_1_1hash_3_01Mirai_1_1QQ__t_01_4" ]
    ] ]
];