var hierarchy =
[
    [ "Mirai::MiraiClient::_has_type_< T >", "classMirai_1_1MiraiClient_1_1__has__type__.html", null ],
    [ "Mirai::MessageChain::_has_type_< T >", "classMirai_1_1MessageChain_1_1__has__type__.html", null ],
    [ "Mirai::ClientConnectionClosedEvent", "structMirai_1_1ClientConnectionClosedEvent.html", null ],
    [ "Mirai::ClientConnectionErrorEvent", "structMirai_1_1ClientConnectionErrorEvent.html", null ],
    [ "Mirai::ClientConnectionEstablishedEvent", "structMirai_1_1ClientConnectionEstablishedEvent.html", null ],
    [ "Mirai::ClientParseErrorEvent", "structMirai_1_1ClientParseErrorEvent.html", null ],
    [ "Mirai::EventBase", "classMirai_1_1EventBase.html", [
      [ "Mirai::BotEvent", "classMirai_1_1BotEvent.html", [
        [ "Mirai::BotOfflineEventActive", "classMirai_1_1BotOfflineEventActive.html", null ],
        [ "Mirai::BotOfflineEventDropped", "classMirai_1_1BotOfflineEventDropped.html", null ],
        [ "Mirai::BotOfflineEventForce", "classMirai_1_1BotOfflineEventForce.html", null ],
        [ "Mirai::BotOnlineEvent", "classMirai_1_1BotOnlineEvent.html", null ],
        [ "Mirai::BotReloginEvent", "classMirai_1_1BotReloginEvent.html", null ]
      ] ],
      [ "Mirai::BotGroupPermissionChangeEvent", "classMirai_1_1BotGroupPermissionChangeEvent.html", null ],
      [ "Mirai::BotInvitedJoinGroupRequestEvent", "classMirai_1_1BotInvitedJoinGroupRequestEvent.html", null ],
      [ "Mirai::BotJoinGroupEvent", "classMirai_1_1BotJoinGroupEvent.html", null ],
      [ "Mirai::BotLeaveEventActive", "classMirai_1_1BotLeaveEventActive.html", null ],
      [ "Mirai::BotLeaveEventDisband", "classMirai_1_1BotLeaveEventDisband.html", null ],
      [ "Mirai::BotLeaveEventKick", "classMirai_1_1BotLeaveEventKick.html", null ],
      [ "Mirai::BotMuteEvent", "classMirai_1_1BotMuteEvent.html", null ],
      [ "Mirai::BotUnmuteEvent", "classMirai_1_1BotUnmuteEvent.html", null ],
      [ "Mirai::CommandExecutedEvent", "classMirai_1_1CommandExecutedEvent.html", null ],
      [ "Mirai::FriendInputStatusChangedEvent", "classMirai_1_1FriendInputStatusChangedEvent.html", null ],
      [ "Mirai::FriendMessageEvent", "classMirai_1_1FriendMessageEvent.html", null ],
      [ "Mirai::FriendNickChangedEvent", "classMirai_1_1FriendNickChangedEvent.html", null ],
      [ "Mirai::FriendRecallEvent", "classMirai_1_1FriendRecallEvent.html", null ],
      [ "Mirai::FriendSyncMessageEvent", "classMirai_1_1FriendSyncMessageEvent.html", null ],
      [ "Mirai::GroupAllowAnonymousChatEvent", "classMirai_1_1GroupAllowAnonymousChatEvent.html", null ],
      [ "Mirai::GroupAllowConfessTalkEvent", "classMirai_1_1GroupAllowConfessTalkEvent.html", null ],
      [ "Mirai::GroupAllowMemberInviteEvent", "classMirai_1_1GroupAllowMemberInviteEvent.html", null ],
      [ "Mirai::GroupEntranceAnnouncementChangeEvent", "classMirai_1_1GroupEntranceAnnouncementChangeEvent.html", null ],
      [ "Mirai::GroupMessageEvent", "classMirai_1_1GroupMessageEvent.html", null ],
      [ "Mirai::GroupMuteAllEvent", "classMirai_1_1GroupMuteAllEvent.html", null ],
      [ "Mirai::GroupNameChangeEvent", "classMirai_1_1GroupNameChangeEvent.html", null ],
      [ "Mirai::GroupRecallEvent", "classMirai_1_1GroupRecallEvent.html", null ],
      [ "Mirai::GroupSyncMessageEvent", "classMirai_1_1GroupSyncMessageEvent.html", null ],
      [ "Mirai::MemberCardChangeEvent", "classMirai_1_1MemberCardChangeEvent.html", null ],
      [ "Mirai::MemberHonorChangeEvent", "classMirai_1_1MemberHonorChangeEvent.html", null ],
      [ "Mirai::MemberJoinEvent", "classMirai_1_1MemberJoinEvent.html", null ],
      [ "Mirai::MemberJoinRequestEvent", "classMirai_1_1MemberJoinRequestEvent.html", null ],
      [ "Mirai::MemberLeaveEventKick", "classMirai_1_1MemberLeaveEventKick.html", null ],
      [ "Mirai::MemberLeaveEventQuit", "classMirai_1_1MemberLeaveEventQuit.html", null ],
      [ "Mirai::MemberMuteEvent", "classMirai_1_1MemberMuteEvent.html", null ],
      [ "Mirai::MemberPermissionChangeEvent", "classMirai_1_1MemberPermissionChangeEvent.html", null ],
      [ "Mirai::MemberSpecialTitleChangeEvent", "classMirai_1_1MemberSpecialTitleChangeEvent.html", null ],
      [ "Mirai::MemberUnmuteEvent", "classMirai_1_1MemberUnmuteEvent.html", null ],
      [ "Mirai::NewFriendRequestEvent", "classMirai_1_1NewFriendRequestEvent.html", null ],
      [ "Mirai::NudgeEvent", "classMirai_1_1NudgeEvent.html", null ],
      [ "Mirai::OtherClientMessageEvent", "classMirai_1_1OtherClientMessageEvent.html", null ],
      [ "Mirai::OtherClientOfflineEvent", "classMirai_1_1OtherClientOfflineEvent.html", null ],
      [ "Mirai::OtherClientOnlineEvent", "classMirai_1_1OtherClientOnlineEvent.html", null ],
      [ "Mirai::StrangerMessageEvent", "classMirai_1_1StrangerMessageEvent.html", null ],
      [ "Mirai::StrangerSyncMessageEvent", "classMirai_1_1StrangerSyncMessageEvent.html", null ],
      [ "Mirai::TempMessageEvent", "classMirai_1_1TempMessageEvent.html", null ],
      [ "Mirai::TempSyncMessageEvent", "classMirai_1_1TempSyncMessageEvent.html", null ]
    ] ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "Mirai::MiraiApiHttpException", "classMirai_1_1MiraiApiHttpException.html", [
          [ "Mirai::AuthKeyFail", "classMirai_1_1AuthKeyFail.html", null ],
          [ "Mirai::BotMuted", "classMirai_1_1BotMuted.html", null ],
          [ "Mirai::IllegalSession", "classMirai_1_1IllegalSession.html", null ],
          [ "Mirai::MessageTooLarge", "classMirai_1_1MessageTooLarge.html", null ],
          [ "Mirai::NoBot", "classMirai_1_1NoBot.html", null ],
          [ "Mirai::NoElement", "classMirai_1_1NoElement.html", null ],
          [ "Mirai::NoOperateSupport", "classMirai_1_1NoOperateSupport.html", null ],
          [ "Mirai::NoSuchFile", "classMirai_1_1NoSuchFile.html", null ],
          [ "Mirai::NotVerifySession", "classMirai_1_1NotVerifySession.html", null ],
          [ "Mirai::PermissionDenied", "classMirai_1_1PermissionDenied.html", null ]
        ] ],
        [ "Mirai::NetworkException", "classMirai_1_1NetworkException.html", null ],
        [ "Mirai::ParseError", "classMirai_1_1ParseError.html", null ],
        [ "Mirai::TypeDismatch", "classMirai_1_1TypeDismatch.html", null ]
      ] ]
    ] ],
    [ "Mirai::FileInfo", "structMirai_1_1FileInfo.html", null ],
    [ "Mirai::FilePath", "classMirai_1_1FilePath.html", null ],
    [ "Mirai::GroupAnnouncement", "structMirai_1_1GroupAnnouncement.html", null ],
    [ "Mirai::GroupConfig", "structMirai_1_1GroupConfig.html", null ],
    [ "Mirai::GroupFileInfo", "structMirai_1_1GroupFileInfo.html", null ],
    [ "std::hash< Mirai::GID_t >", "structstd_1_1hash_3_01Mirai_1_1GID__t_01_4.html", null ],
    [ "std::hash< Mirai::QQ_t >", "structstd_1_1hash_3_01Mirai_1_1QQ__t_01_4.html", null ],
    [ "Mirai::MessageChain", "classMirai_1_1MessageChain.html", null ],
    [ "Mirai::MiraiClient", "classMirai_1_1MiraiClient.html", null ],
    [ "Mirai::NudgeTarget", "classMirai_1_1NudgeTarget.html", null ],
    [ "Mirai::Serializable", "classMirai_1_1Serializable.html", [
      [ "Mirai::ClientDevice", "structMirai_1_1ClientDevice.html", null ],
      [ "Mirai::ForwardMessage::Node", "classMirai_1_1ForwardMessage_1_1Node.html", null ],
      [ "Mirai::Group", "structMirai_1_1Group.html", null ],
      [ "Mirai::GroupMember", "structMirai_1_1GroupMember.html", null ],
      [ "Mirai::MessageBase", "classMirai_1_1MessageBase.html", [
        [ "Mirai::AppMessage", "classMirai_1_1AppMessage.html", null ],
        [ "Mirai::AtAllMessage", "classMirai_1_1AtAllMessage.html", null ],
        [ "Mirai::AtMessage", "classMirai_1_1AtMessage.html", null ],
        [ "Mirai::AudioMessage", "classMirai_1_1AudioMessage.html", null ],
        [ "Mirai::DiceMessage", "classMirai_1_1DiceMessage.html", null ],
        [ "Mirai::FaceMessage", "classMirai_1_1FaceMessage.html", [
          [ "Mirai::MarketFaceMessage", "classMirai_1_1MarketFaceMessage.html", null ]
        ] ],
        [ "Mirai::FileMessage", "classMirai_1_1FileMessage.html", null ],
        [ "Mirai::ForwardMessage", "classMirai_1_1ForwardMessage.html", null ],
        [ "Mirai::ImageMessage", "classMirai_1_1ImageMessage.html", [
          [ "Mirai::FlashImageMessage", "classMirai_1_1FlashImageMessage.html", null ]
        ] ],
        [ "Mirai::JsonMessage", "classMirai_1_1JsonMessage.html", null ],
        [ "Mirai::MiraiCodeMessage", "classMirai_1_1MiraiCodeMessage.html", null ],
        [ "Mirai::MusicShareMessage", "classMirai_1_1MusicShareMessage.html", null ],
        [ "Mirai::PlainMessage", "classMirai_1_1PlainMessage.html", null ],
        [ "Mirai::PokeMessage", "classMirai_1_1PokeMessage.html", null ],
        [ "Mirai::QuoteMessage", "classMirai_1_1QuoteMessage.html", null ],
        [ "Mirai::SourceMessage", "classMirai_1_1SourceMessage.html", null ],
        [ "Mirai::XmlMessage", "classMirai_1_1XmlMessage.html", null ]
      ] ],
      [ "Mirai::MiraiAudio", "structMirai_1_1MiraiAudio.html", null ],
      [ "Mirai::MiraiImage", "structMirai_1_1MiraiImage.html", null ],
      [ "Mirai::User", "structMirai_1_1User.html", null ],
      [ "Mirai::UserProfile", "structMirai_1_1UserProfile.html", null ]
    ] ],
    [ "Mirai::SessionConfigs", "structMirai_1_1SessionConfigs.html", null ],
    [ "Mirai::MessageChain::SourceInfo", "structMirai_1_1MessageChain_1_1SourceInfo.html", null ],
    [ "Mirai::UID_t", "classMirai_1_1UID__t.html", [
      [ "Mirai::GID_t", "classMirai_1_1GID__t.html", null ],
      [ "Mirai::QQ_t", "classMirai_1_1QQ__t.html", null ]
    ] ]
];